/**
 * A szállítók - OpenAPI 3.0
 * API documentation for the backend of The Transporters project
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface Delivery {
    id?: number;
    title?: string;
    description?: string;
    sourceLocation?: Location;
    destinationLocation?: Location;
    clientUserId?: number;
    transporterUserId?: number;
    pickUpFrom?: Date;
    pickUpUntil?: Date;
    price?: number;
    clientRating?: number;
    transporterRating?: number;
    weight?: number;
    height?: number;
    length?: number;
    width?: number;
    status?: string;
    pictureUrl?: string;
    createdAt?: string;
    updatedAt?: string;
}