/**
 * A szállítók - OpenAPI 3.0
 * API documentation for the backend of The Transporters project
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User {
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    googletoken: string;
    phoneNumber: string;
    vehicleId?: number;
    isAdmin: boolean;
    profilePictureUrl?: string;
}